name: MakeCode Arcade Release

on: 
  release:
    types:
      - created

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install MakeCode
        run: |
          npm install -g pxt
          pxt target arcade

      - name: Build Web Game (HTML)
        run: |
          pxt staticpkg --output dist

      - name: Build D51
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw samd51
          pxt build --hw samd51 --cloud
          cp ./built/binary.uf2 binary-d51.uf2

      - name: Build F4
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw stm32f401
          pxt build --hw stm32f401 --cloud
          cp ./built/binary.uf2 binary-f4.uf2

      - name: Build P0
        continue-on-error: true
        run: |
          pxt clean
          pxt install --hw rpi
          pxt build --hw rpi --cloud
          cp ./built/binary.uf2 binary-p0.uf2

      - name: Bundle all binaries
        run: |
          cat binary-*.uf2 > built/arcade.uf2

      - name: Upload Bundled Binaries to Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./built/arcade.uf2

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master  # Deploy to master branch
          folder: dist  # The output folder containing index.html
          